enum OBJECT_TYPE { 
	TYPE, 
	LIST, QUADTREE,			//level lists
	
	DYNAMIC,				//objects
	
	POINT, CIRCLE, LINE,	//primitives
	RECTANGLE, POLYGON		
};

//collisions map
globalvar POINT_COLLISIONS;
POINT_COLLISIONS = [];

POINT_COLLISIONS[OBJECT_TYPE.POINT] = point_in_point;
POINT_COLLISIONS[OBJECT_TYPE.CIRCLE] = point_in_circle;
POINT_COLLISIONS[OBJECT_TYPE.LINE] = point_in_line;
POINT_COLLISIONS[OBJECT_TYPE.RECTANGLE] = point_in_rectangle;
POINT_COLLISIONS[OBJECT_TYPE.POLYGON] = point_in_polygon;
POINT_COLLISIONS[OBJECT_TYPE.DYNAMIC] = point_in_dynamic;

globalvar CIRCLE_COLLISIONS;
CIRCLE_COLLISIONS = [];

CIRCLE_COLLISIONS[OBJECT_TYPE.POINT] = circle_in_point;
CIRCLE_COLLISIONS[OBJECT_TYPE.CIRCLE] = circle_in_circle;
CIRCLE_COLLISIONS[OBJECT_TYPE.LINE] = circle_in_line;
CIRCLE_COLLISIONS[OBJECT_TYPE.RECTANGLE] = circle_in_rectangle;
CIRCLE_COLLISIONS[OBJECT_TYPE.POLYGON] = circle_in_polygon;

globalvar LINE_COLLISIONS;
LINE_COLLISIONS = [];

LINE_COLLISIONS[OBJECT_TYPE.POINT] = line_in_point;
LINE_COLLISIONS[OBJECT_TYPE.CIRCLE] = line_in_circle;
LINE_COLLISIONS[OBJECT_TYPE.LINE] = line_in_line;
LINE_COLLISIONS[OBJECT_TYPE.RECTANGLE] = line_in_rectangle;
LINE_COLLISIONS[OBJECT_TYPE.POLYGON] = line_in_polygon;


globalvar RECTANGLE_COLLISIONS;
RECTANGLE_COLLISIONS = [];

RECTANGLE_COLLISIONS[OBJECT_TYPE.POINT] = rectangle_in_point;
RECTANGLE_COLLISIONS[OBJECT_TYPE.CIRCLE] = rectangle_in_circle;
RECTANGLE_COLLISIONS[OBJECT_TYPE.LINE] = rectangle_in_line;
RECTANGLE_COLLISIONS[OBJECT_TYPE.RECTANGLE] = rectangle_in_rectangle;
RECTANGLE_COLLISIONS[OBJECT_TYPE.POLYGON] = rectangle_in_polygon;

globalvar POLYGON_COLLISIONS;
POLYGON_COLLISIONS = [];

POLYGON_COLLISIONS[OBJECT_TYPE.POINT] = polygon_in_point;
POLYGON_COLLISIONS[OBJECT_TYPE.CIRCLE] = polygon_in_circle;
POLYGON_COLLISIONS[OBJECT_TYPE.LINE] = polygon_in_line;
POLYGON_COLLISIONS[OBJECT_TYPE.RECTANGLE] = polygon_in_rectangle;
POLYGON_COLLISIONS[OBJECT_TYPE.POLYGON] = polygon_in_polygon;


globalvar COLLISIONS_MAP;
COLLISIONS_MAP = [];

COLLISIONS_MAP[OBJECT_TYPE.POINT] = POINT_COLLISIONS;
COLLISIONS_MAP[OBJECT_TYPE.CIRCLE] = CIRCLE_COLLISIONS;
COLLISIONS_MAP[OBJECT_TYPE.LINE] = LINE_COLLISIONS;
COLLISIONS_MAP[OBJECT_TYPE.RECTANGLE] = RECTANGLE_COLLISIONS;
COLLISIONS_MAP[OBJECT_TYPE.POLYGON] = POLYGON_COLLISIONS;

//collision test state machine inspired by colmesh
function collision_test(a, b){
	var object_tests = COLLISIONS_MAP[ a[OBJECT_TYPE.TYPE]];
	var test = object_tests[ b[OBJECT_TYPE.TYPE]];
	
	return test(a, b);
}

function Level(){
	
}