enum OBJECT_TYPE { TYPE, POINT, CIRCLE, LINE, RECTANGLE, POLYGON, CAPSULE };

//collisions map
globalvar POINT_COLLISIONS;
POINT_COLLISIONS = [];

POINT_COLLISIONS[OBJECT_TYPE.POINT] = point_in_point;
POINT_COLLISIONS[OBJECT_TYPE.CIRCLE] = point_in_circle;
POINT_COLLISIONS[OBJECT_TYPE.LINE] = point_in_line;
POINT_COLLISIONS[OBJECT_TYPE.RECTANGLE] = point_in_rectangle;
POINT_COLLISIONS[OBJECT_TYPE.POLYGON] = point_in_polygon;

globalvar CIRCLE_COLLISIONS;
CIRCLE_COLLISIONS = [];

CIRCLE_COLLISIONS[OBJECT_TYPE.POINT] = circle_in_point;
CIRCLE_COLLISIONS[OBJECT_TYPE.CIRCLE] = circle_in_circle;
CIRCLE_COLLISIONS[OBJECT_TYPE.LINE] = circle_in_line;

globalvar LINE_COLLISIONS;
LINE_COLLISIONS = [];

LINE_COLLISIONS [OBJECT_TYPE.LINE] = line_in_line;
LINE_COLLISIONS [OBJECT_TYPE.POLYGON] = line_in_polygon;

globalvar COLLISIONS_MAP;
COLLISIONS_MAP = [];

COLLISIONS_MAP[OBJECT_TYPE.POINT] = POINT_COLLISIONS;
COLLISIONS_MAP[OBJECT_TYPE.LINE] = LINE_COLLISIONS;

//collision test state machine inspired by colmesh
function collision_test(a, b){
	var object_tests = COLLISIONS_MAP[ a[OBJECT_TYPE.TYPE]];
	var test = object_tests[ b[OBJECT_TYPE.TYPE]];
	
	return test(a, b);
}

function Level(){
	
}